[versions]
# Android-App
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

# Project
agp = "8.13.2"
androidx-activity = "1.12.2"
androidx-lifecycle = "2.9.6"
androidx-security = "1.1.0"
kotlin = "2.3.0"
kotlinStdlib = "2.3.0"

# KMP Libraries
coroutines = "1.10.2"
datetime = "0.7.1"
decompose = "3.4.0"
koin = "4.1.1"
serialization = "1.10.0"
sqldelight = "2.2.1"
multiplatformSettings = "1.3.0"
napier = "2.7.1"

# Compose Multiplatgorm
composeMultiplatform = "1.10.0"
foundation = "1.10.0"
material3 = "1.9.0"
resources = "1.10.0"
runtime = "1.10.0"
ui = "1.10.0"

[libraries]

# Koin - DI
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }

# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

# Serialization
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

# DateTime
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }

# SQLDelight
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native = { module = "app.cash.sqldelight:native-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-primitive = { module = "app.cash.sqldelight:primitive-adapters", version.ref = "sqldelight" }

# Multiplatform Settings
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "androidx-security" }

# Napier
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

# Decompose
decompose = { module = "com.arkivanov.decompose:decompose", version.ref = "decompose" }
decompose-android = { module = "com.arkivanov.decompose:extensions-android", version.ref = "decompose" }
decompose-compose-extensions = { module = "com.arkivanov.decompose:extensions-compose", version.ref = "decompose" }

# Compose Multiplatform
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "resources" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "foundation" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "runtime" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "ui" }

# Android Specific
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidLint = { id = "com.android.lint", version.ref = "agp" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }
